/**
 * Scene Dialogue Data - Character-specific dialogue for game scenes
 * 
 * This module contains character-specific dialogue that varies based on the
 * player's chosen character. Each character has their own unique storyline.
 */

// Dario's plot - Original protagonist storyline
export const DARIO_SCENE_DIALOGUE: Record<string, string[]> = {
  "1": [
    "DARIO IS A FRESH WET TRANSFER STUDENT",
    "TRYING TO NAVIGATE HIS WAY AT A NEW SCHOOL...",
    "OUTHERE ACADEMY.",
  ],
  "3": [
    "AFTER FIGHTING TO GET TO HIS LOCKER... ",
    "DARIO SEES ANGELA... THE MOST BEAUTIFUL GIRL",
    "HE HAD EVER SEEN IN HIS LIFE. ONLY ONE PROBLEM...",
    "SHE HAD NO CLUE WHO HE EVEN WAS. HE MAKES IT HIS",
    "MISSION TO GET THIS GIRL. TRYING HIS BEST HE SAYS",
    "``HEY I`M DARIO`` - HOPING TO GET HER ATTENTION...",
    "BUT SHE JUST WALKS AWAY.",
  ],
  "6": [
    "TONY CONFRONTS DARIO FOR TALKING",
    "TO HIS GIRL ANGELA. TONY LETS HIM KNOW",
    "THAT HE IS THE GUY ON CAMPUS.",
    "DARIO BETTER WATCH HIMSELF UNLESS HE WANTS",
    "HEAT. TONY LEAVES AFTER STARTING A FIGHT.",
    "DARIO CONINUES THROUGH THE SCHOOL.",
  ],
  "8": [
    "DOCTOR MIDNIGHT JOHNSON IS ALREADY",
    "FED UP WITH DARIO`S BEHAVIOR. A NEW KID IS NOT",
    "GOING TO DISRUPT HIS CLASSROOM...",
    "``WHY ARE YOU LATE...?`` - THE DOCTOR ASKS.",
    "WITH NO RESPONSE... DARIO DECIDES TO ACT OUT...",
  ],
  "9": [
    "DARIO GETS REPREMANDED BY THE PRINCIPLE FOR FIGHTING.",
    "EVEN THOUGH HE WAS GIVEN ANOTHER CHANCE... ",
    "ALL DARIO COULD THINK ABOUT IS ANGELA...",
    "HE CONTINUES THROUGH THE SCHOOL HOPING TO RUN",
    "INTO HER AGAIN.",
  ],
  "12": [
    "DARIO SEES ANGELA AFTER THE FIGHT",
    "WITH DOCTOR MIDNIGHT. DARIO IS HEAD OVER",
    "HEELS FOR ANGELA. THE LOOK SHE GAVE HIM AFTER",
    "BEATING UP TONY LET HIM KNOW THAT ONE DAY...",
    "SHE WOULD BE HIS GIRL.",
    "``HEY DARIO`` IS ALL ANGELA HAD TO SAY...",
  ],
  "13": [
    "TONY CONFRONTS DARIO IN THE HALLWAY AND",
    "CHALLENGES HIM TO A FIGHT OVER ANGELA. TONY SAYS",
    "``IF YOU WANT MY GIRL YOU HAVE TO FIGHT ME FOR HER.``",
    "DARIO HAS TO MEET HIM IN THE BASEMENT AFTER SCHOOL",
    "FOR THE BIG FIGHT.",
  ],
  "14": [
    "DARIO GETS TO THE BASEMENT AND STANDING THERE",
    "IS THE PRINCIPLE, ANGELA, TONY AND THE POLICE.",
    "IT TURNS OUT THE LOOK SHE GAVE HIM AFTER BEATING",
    "TONY UP WAS A WARNING... TONY HAD USED THE",
    "FIGHT TO GET DARIO INTO SERIOUS TROUBLE.",
  ],
  "16": [
    "AFTER FIGHTING THE POLICE AND THE PRINCIPLE,",
    "DARIO EXITS THE SCHOOL. DARIO FELL INTO AN",
    "AMBUSH THAT TONY HAD SET UP. ALL OF THAT",
    "BECAUSE DARIO TALKED TO HIS GIRL. THE WHOLE",
    "SCHOOL IS WATCHING AS DARIO GETS KARTED OFF",
    "BY A POLICE CAR. TONY STANDS THERE",
    "AS THEY TAKE DARIO AWAY...",
  ],
  "17": [
    "DARIO WAKES UP IN PRISON AFTER BEING SET UP BY",
    "TONY. ONCE TONY REALIZED DARIO WAS A THREAT, HE",
    "SET OUT TO DESTROY HIM AND SUCCEEDED. AFTER SOME",
    "TIME BEHIND BARS, DARIO DECIDED HE`D HAD ENOUGH...",
    "HE WANTS TO BREAK OUT.",
  ],
  "19": [
    "DARIO RUNS INTO A CORRECTIONS OFFICER THAT",
    "IS FAMILIAR WITH HIS STORY... TURNS OUT THEY",
    "GREW UP TOGETHER. AFTER, THE OFFICER TELLS DARIO",
    "WHAT HE NEEDS TO DO IN ORDER TO ESCAPE...",
    "OUTHERE PENITENTIARY.",
  ],
  "20": [
    "DARIO MEETS BIG BEN IN THE DINNING HALL TO FORMULATE",
    "A PLAN FOR HIS ESCAPE. BUT FIRST... DARIO HAS TO DO",
    "BIG BEN A FAVOR...",
  ],
  "22": [
    "DARIO HELD UP HIS END OF THE DEAL AND FOUGHT A",
    "CORRECTIONAL OFFICER IN EXCHANGE FOR BIG BEN",
    "HELPING HIM BREAK FREE... DEAL WITH BIG BEN. AFTER",
    "BREAKING OUT... THE ONLY THING ON HIS MIND WAS FINDING",
    "TONY AND GETTING HIM BACK FOR WHAT HE DID.",
  ],
  "24": [
    "DARIO SEES ANGELA AT THE BUS STOP AFTER BREAKING",
    "OUT OF PRISON. HE WAS ON HIS WAY TO SCHOOL TO FIND",
    "TONY AND FIGHT HIM FOR WHAT HE DID... ANGELA CONFRONTS",
    "DARIO TRYING TO STOP HIM FROM FIGHTING BUT",
    "SHE FAILS TO STOP HIM... HE IS ON A MISSION",
    "TO FIND TONY...",
  ],
  "25": [
    "DARIO SEES TONY AND THEY BOTH KNOW HOW THIS",
    "MEETING ENDS... ONE PERSON IN THE HOSPITAL...",
    "AND THE OTHER ONE WITH ANGELA. IT WAS TIME",
    "FOR DARIO TO FINALLY GET HIS REVENGE.",
  ],
  "26": [
    "DARIO SEES ANGELA AFTER BEATING TONY IN THE FIGHT.",
    "``SO YOU DID ALL OF THAT FOR ME?`` - ANGELA SAID.",
    "``YEAH... WAS IT WORTH IT?`` - DARIO RESPONDS.",
    "ANGELA PAUSES FOR A MOMENT THEN SAID... ",
    "``LETS FIND OUT...``",
  ],
  "27": [
    "THEY WENT BACK TO THE CRIB ON OUTHERE STREET",
    "AND LIVED HAPPILY EVER AFTER...",
    " ",
    " ",
    "THE END.",
  ],
};

// Axel's plot
export const AXEL_SCENE_DIALOGUE: Record<string, string[]> = {
  "1": [
    "AXEL IS A FRESH WET TRANSFER STUDENT",
    "TRYING TO NAVIGATE HIS WAY AT A NEW SCHOOL...",
    "OUTHERE ACADEMY.",
  ],
  "3": [
    "AFTER FIGHTING TO GET TO HIS LOCKER... ",
    "AXEL SEES ANGELA... THE MOST BEAUTIFUL GIRL",
    "HE HAD EVER SEEN IN HIS LIFE. ONLY ONE PROBLEM...",
    "SHE HAD NO CLUE WHO HE EVEN WAS. HE MAKES IT HIS",
    "MISSION TO GET THIS GIRL. TRYING HIS BEST HE SAYS",
    "``HEY I`M AXEL`` - HOPING TO GET HER ATTENTION...",
    "BUT SHE JUST WALKS AWAY.",
  ],
};

// Blaze's plot
export const BLAZE_SCENE_DIALOGUE: Record<string, string[]> = {
  "1": [
    "BLAZE IS A FRESH WET TRANSFER STUDENT ",
    "TRYING TO NAVIGATE HER WAY AT A NEW SCHOOL...",
    "OUTHERE ACADEMY.",
  ],
  "3": [
    "AFTER FIGHTING TO GET TO HER LOCKER... ",
    "BLAZE SEES ANGELA... THE MOST BEAUTIFUL GIRL ",
    "SHE HAD EVER SEEN IN HER LIFE. ONLY ONE PROBLEM... ",
    "SHE HAD NO CLUE WHO SHE EVEN WAS. SHE MAKES IT HER ",
    "MISSION TO GET THIS GIRL. TRYING HER BEST SHE SAYS ",
    "``HEY I`M BLAZE`` - HOPING TO GET HER ATTENTION... ",
    "BUT SHE JUST WALKS AWAY.",
  ],
};

// Max's plot
export const MAX_SCENE_DIALOGUE: Record<string, string[]> = {
  "1": [
    "MAX IS A FRESH WET TRANSFER STUDENT",
    "TRYING TO NAVIGATE HIS WAY AT A NEW SCHOOL...",
    "OUTHERE ACADEMY.",
  ],
  "3": [
    "AFTER FIGHTING TO GET TO HIS LOCKER... ",
    "MAX SEES ANGELA... THE MOST BEAUTIFUL GIRL",
    "HE HAD EVER SEEN IN HIS LIFE. ONLY ONE PROBLEM...",
    "SHE HAD NO CLUE WHO HE EVEN WAS. HE MAKES IT HIS",
    "MISSION TO GET THIS GIRL. TRYING HIS BEST HE SAYS",
    "``HEY I`M MAX`` - HOPING TO GET HER ATTENTION...",
    "BUT SHE JUST WALKS AWAY.",
  ],
};

// Sammy's plot
export const SAMMY_SCENE_DIALOGUE: Record<string, string[]> = {
  "1": [
    "SAMMY IS A FRESH WET TRANSFER STUDENT",
    "TRYING TO NAVIGATE HER WAY AT A NEW SCHOOL...",
    "OUTHERE ACADEMY.",
  ],
  "3": [
    "AFTER FIGHTING TO GET TO HER LOCKER... ",
    "SAMMY SEES ANGELA... THE MOST BEAUTIFUL GIRL",
    "SHE HAD EVER SEEN IN HER LIFE. ONLY ONE PROBLEM...",
    "SHE HAD NO CLUE WHO SHE EVEN WAS. SHE MAKES IT HER",
    "MISSION TO GET THIS GIRL. TRYING HER BEST SHE SAYS",
    "``HEY I`M SAMMY`` - HOPING TO GET HER ATTENTION...",
    "BUT SHE JUST WALKS AWAY.",
  ],
};

// Character dialogue mapping
const CHARACTER_DIALOGUE_MAP: Record<string, Record<string, string[]>> = {
  'dario': DARIO_SCENE_DIALOGUE,
  'axel': AXEL_SCENE_DIALOGUE,
  'blaze': BLAZE_SCENE_DIALOGUE,
  'max': MAX_SCENE_DIALOGUE,
  'sammy': SAMMY_SCENE_DIALOGUE,
};

// Default - maps to Dario's plot
export const SCENE_DIALOGUE = DARIO_SCENE_DIALOGUE;

/**
 * Get scene dialogue for a character
 */
export function getSceneDialogue(character: string, sceneKey: string): string[] {
  const normalizedChar = character.toLowerCase();
  const charDialogue = CHARACTER_DIALOGUE_MAP[normalizedChar];
  
  if (charDialogue && charDialogue[sceneKey]) {
    return charDialogue[sceneKey];
  }
  
  // Fallback to Dario's dialogue if character-specific dialogue not found
  return DARIO_SCENE_DIALOGUE[sceneKey] || [];
}

